### PR TITLE
Add `bin_mask` parameter to gate.density2d() to facilitate the reuse of density gates

### PR DESCRIPTION
**Pull request by JS3xton**
Introduce a `DensityGate` class, which is returned from and can be reused with `gate.density2d`. 

Closes https://github.com/taborlab/FlowCal/issues/267.
<br>
#### Rationale
Keeping track of different density gates seemed like a prime opportunity for object-oriented programming, so I introduced our first gate class. I tried to keep it simple (I started with a `namedtuple`, but ultimately wanted richer equality and hash functions and a clear docstring).

I hid the `_bin_edges` and `_accepted_bin_indices` attributes because they're implementation-specific and could theoretically change in the future.

I revealed the `boundaries` attribute because users might want to know how to visualize the gate boundaries. I chose "boundaries" over "contours" because boundaries [appears to be the more general multi-dimensional word for contours](https://en.wikipedia.org/wiki/Boundary_(topology)) (I didn't change contours anywhere it's already in use, though).

I tried to be as specific and general as possible in describing the attribute data types (see `DensityGate` docstring) without imposing additional constraints on existing data structures.
<br>
#### Testing
Many new unit tests were written, and they all pass in `Python 3.8 + Anaconda 2020.02` and `Python 2.7 + Anaconda 4.4.0`.

The following script, which applies a density gate trained on one data set to another data set, also appears to produce the correct output:
```python
import FlowCal as fc
import matplotlib.pyplot as plt

d2 = fc.io.FCSData('./examples/FCFiles/Data002.fcs')
d3 = fc.io.FCSData('./examples/FCFiles/Data003.fcs')
d2 = fc.transform.to_rfi(d2)
d3 = fc.transform.to_rfi(d3)

out2 = fc.gate.density2d(d2, channels=['FSC','FL1'], gate_fraction=0.5, full_output=True)
out3_gate2 = fc.gate.density2d(d3, channels=['FSC','FL1'], density_gate=out2.density_gate, full_output=True)

fig,ax = plt.subplots(nrows=2, ncols=2, figsize=(7,7))
plt.sca(ax[0,0])
fc.plot.density2d(d2, channels=['FSC', 'FL1'], title=d2.infile, mode='scatter')
for cntr in out2.density_gate.boundaries:
    plt.plot(cntr[:,0], cntr[:,1], color='red')
plt.sca(ax[0,1])
fc.plot.density2d(d3, channels=['FSC', 'FL1'], title=d3.infile, mode='scatter')
for cntr in out2.density_gate.boundaries:
    plt.plot(cntr[:,0], cntr[:,1], color='red')
plt.sca(ax[1,0])
fc.plot.density2d(out2.gated_data, channels=['FSC', 'FL1'], title='Gated w/ Data002.fcs density gate', mode='scatter')
for cntr in out2.density_gate.boundaries:
    plt.plot(cntr[:,0], cntr[:,1], color='red')
plt.sca(ax[1,1])
fc.plot.density2d(out3_gate2.gated_data, channels=['FSC', 'FL1'], title='Gated w/ Data002.fcs density gate', mode='scatter')
for cntr in out3_gate2.density_gate.boundaries:
    plt.plot(cntr[:,0], cntr[:,1], color='red')

plt.tight_layout()
plt.savefig('reuse_density_gate.png', dpi=600.0)
```
reuse_density_gate

<br>
We may also want to mention this functionality in the tutorial somewhere, but I couldn't find an obvious place to put it.

### CODE REVIEW

**Comment by castillohair** [comment]
I am not convinced that an object is the right data structure for this. Objects should contain data and perform operations, but `DensityGate` does not contain any methods other than the boilerplate equality functions. I would prefer if `bin_edges` and `accepted_bin_indices` are direct arguments to `density2d()`. This would make it more consistent with the function-oriented nature of the module, where the arguments are simple and no objects other than `FCSData` are involved. In addition, it would directly signal the user that these arguments can be generated from scratch, although why they would do this is not clear to me.

Also, would it be better to change `accepted_bin_indices` to something like `bin_mask`? We're using `mask` as the name of one of the outputs already, and this is kind of a similar concept although applied to a different axis.

**Comment by JS3xton** [comment]
> I would prefer if `bin_edges` and `accepted_bin_indices` are direct arguments to `density2d()`. This would make it more consistent with the function-oriented nature of the module

Hmm, I like preserving the function-oriented nature of the module, but how would one reuse gates? Would one have to keep track of multiple different `bin_edges` and their associated `accepted_bin_indices`? That seems kludge to me.

We ultimately have to define an API for specifying density gates, and I see a trade-off between consistency and simplicity. Here, I favor simplicity; I thought specifying `bin_edges` and `accepted_bin_indices` was too complicated for a normal (casual) user and offering them a black-box `DensityGate` class would be simpler. Moreover, the underlying implementation could change and break the API, whereas packaging the necessary underlying data structures into an object would allow seamless modification of the underlying algorithm with no change to the API. I also would not recommend specifying `bin_edges` and `accepted_bin_indices` manually because they are very interrelated and pretty technical (`accepted_bin_indices` must correctly index an unraveled 2D histogram created from `bin_edges`).

So I thought all but the most technical users would prefer to carry around different `DensityGate` instances (e.g. from their control samples) and simply pass them back to `density2d()` and not worry about what's going on under the hood. (And a technical user should be comfortable making their own `DensityGate` instance if it's well documented.)

> Also, would it be better to change `accepted_bin_indices` to something like `bin_mask`? We're using `mask` as the name of one of the outputs already, and this is kind of a similar concept although applied to a different axis.

Hmm, that would certainly make it a lot easier to explain to users, and possibly obviate my desire to hide the implementation details behind a black-box `DensityGate` class. As the algorithm is currently implemented, though, I don't think it's an appropriate description of the data structure.

To me, "mask" implies a Boolean array of the same size as the array being masked. `accepted_bin_indices` is a set of integers (not `bools`), and its length does not match the length of the data structure it is indexing. Moreover, it relies heavily on how numpy unravels 2D arrays, making it hard to specify manually.

If the algorithm could be modified to use a more traditional mask (e.g., a 2D Boolean array—which I think [indexes other 2D arrays of the same size intuitively?](https://numpy.org/doc/stable/user/quickstart.html#indexing-with-boolean-arrays)), then I might be on board with ditching the `DensityGate` class.

**Comment by JS3xton** [comment]
Offline, @castillohair sanctioned adding a proper `bin_mask` parameter to `gate.density2d()` and indicated that a proper mask would be better and more intuitive.

**Comment by JS3xton** [comment]
62efdd028f4ec2273c35d5f5a8f8e8a0e033c572 replaces `DensityGate` with a new `bin_mask` parameter for `gate.density2d()`.

Unit tests were updated accordingly and pass in `Python 3.8 + Anaconda 2020.07` and `Python 2.7 + Anaconda 5.2.0`.

A script applying a density gate trained on one data set to another data set is shown below along with the script output:

<details>
  <summary>script and output</summary>

 ```python
import FlowCal as fc
import matplotlib.pyplot as plt

d2 = fc.io.FCSData('./examples/FCFiles/Data002.fcs')
d3 = fc.io.FCSData('./examples/FCFiles/Data003.fcs')

d2 = fc.transform.to_rfi(d2)
d3 = fc.transform.to_rfi(d3)

out2 = fc.gate.density2d(d2, channels=['FSC','FL1'], gate_fraction=0.5, full_output=True)

plt.figure(figsize=(3,3))
plt.imshow(out2.bin_mask.T, origin='lower', cmap='gray')
plt.xlabel('row index (FSC)')
plt.ylabel('column index (FL1)')
plt.title('`bin_mask`')
plt.tight_layout()
plt.savefig('bin_mask.png', dpi=600.0)
 ```

  

 ```python
out3_gate2 = fc.gate.density2d(d3, channels=['FSC','FL1'], bins=out2.bin_edges, bin_mask=out2.bin_mask, full_output=True)

fig,ax = plt.subplots(nrows=2, ncols=2, figsize=(7,7))

plt.sca(ax[0,0])
fc.plot.density2d(d2, channels=['FSC', 'FL1'], title=d2.infile, mode='scatter')
for cntr in out2.contour:
    plt.plot(cntr[:,0], cntr[:,1], color='red')

plt.sca(ax[0,1])
fc.plot.density2d(d3, channels=['FSC', 'FL1'], title=d3.infile, mode='scatter')
for cntr in out2.contour:
    plt.plot(cntr[:,0], cntr[:,1], color='red')

plt.sca(ax[1,0])
fc.plot.density2d(out2.gated_data, channels=['FSC', 'FL1'], title='Gated w/ Data002.fcs density gate', mode='scatter')
for cntr in out2.contour:
    plt.plot(cntr[:,0], cntr[:,1], color='red')

plt.sca(ax[1,1])
fc.plot.density2d(out3_gate2.gated_data, channels=['FSC', 'FL1'], title='Gated w/ Data002.fcs density gate', mode='scatter')
for cntr in out2.contour:
    plt.plot(cntr[:,0], cntr[:,1], color='red')

plt.tight_layout()
plt.savefig('reuse_density_gate.png', dpi=600.0)
 ```

  

</details>

A note on an arbitrary decision that was made: When `bin_mask` is specified and `full_output==True`, `contour` is set to `None`. I did this because `contour` is calculated from the smoothed density calculated from the data, which is not available if `bin_mask` is specified by the user. This behavior is noted in the docstring.

**Comment by castillohair** [comment]
Running the Excel UI on the example files fails with the following error message:

```
Reading experiment.xlsx...

Processing Beads table (1 entries)
==================================

Beads ID B0001...
Loading file "FCFiles/Beads006.fcs"...
Performing data transformation...
Performing gating...
Traceback (most recent call last):
  File "/Users/castillohair/Documents/Programs/FlowCal-recent/FlowCal/FlowCal/excel_ui.py", line 456, in process_beads_table
    beads_sample_gated, __, gate_contour = FlowCal.gate.density2d(
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/castillohair/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/castillohair/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/castillohair/Documents/Programs/FlowCal-recent/FlowCal/FlowCal/excel_ui.py", line 1710, in <module>
    run_command_line()
  File "/Users/castillohair/Documents/Programs/FlowCal-recent/FlowCal/FlowCal/excel_ui.py", line 1703, in run_command_line
    run(input_path=args.inputpath,
  File "/Users/castillohair/Documents/Programs/FlowCal-recent/FlowCal/FlowCal/excel_ui.py", line 1580, in run
    beads_samples, mef_transform_fxns, mef_outputs = process_beads_table(
  File "/Users/castillohair/Documents/Programs/FlowCal-recent/FlowCal/FlowCal/excel_ui.py", line 465, in process_beads_table
    raise ExcelUIException(ve.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

**Comment by JS3xton** [comment]
Ooo, good catch. Fixed in aca96d8b53b0970f0da23464f7894e5998cd2394.

**Pull request merged**
