### PR TITLE
Incorporated necessary functions from matplotlib to be deprecated

### LINKED ISSUE #312: upcoming matplotlib deprecation of `ticker.decade_up` and `ticker.decade_down`
Running FlowCal with matplotlib 3.1.0 and greater (after fixing #310) gives the following set of warnings:

```
MatplotlibDeprecationWarning: 
The decade_up function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  vmin = -matplotlib.ticker.decade_up(-vmin, b)
/Users/castillohair/Documents/Programs/FlowCal-venv/FlowCal/FlowCal/plot.py:629: MatplotlibDeprecationWarning: 
The decade_up function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  vmax = matplotlib.ticker.decade_up(vmax, b)
/Users/castillohair/Documents/Programs/FlowCal-venv/FlowCal/FlowCal/plot.py:624: MatplotlibDeprecationWarning: 
The decade_down function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  vmin = matplotlib.ticker.decade_down(vmin, b)
Calculating standard curve for channel FL1...
/Users/castillohair/Documents/Programs/FlowCal-venv/FlowCal/FlowCal/plot.py:624: MatplotlibDeprecationWarning: 
The decade_down function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  vmin = matplotlib.ticker.decade_down(vmin, b)
/Users/castillohair/Documents/Programs/FlowCal-venv/FlowCal/FlowCal/plot.py:629: MatplotlibDeprecationWarning: 
The decade_up function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  vmax = matplotlib.ticker.decade_up(vmax, b)
/Users/castillohair/Documents/Programs/FlowCal-venv/FlowCal/FlowCal/plot.py:622: MatplotlibDeprecationWarning: 
The decade_up function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  vmin = -matplotlib.ticker.decade_up(-vmin, b)
```

The `ticker.decade_up` and `ticker.decade_down` functions are used in the [plot](https://github.com/taborlab/FlowCal/blob/develop/FlowCal/plot.py#L620) module to compute the next and previous 10^x number for a given number. Given that these are simple functions, the best solution to me would be to just copy the [code](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/ticker.py#L2242) into "private" functions the plot module.

### PR DESCRIPTION
**Pull request by castillohair**
Fixes #312.

### CODE REVIEW

**Comment by castillohair** [comment]
Note : #311 should be merged before this.

**Comment by castillohair** [comment]
If there are no further comments, I will merge during the weekend.

**Review by JS3xton — COMMENTED** [review]
Did you consider using the new `_decade_less_equal`, `_decade_greater_equal`, `_decade_less`, `_decade_greater` functions that were apparently introduced to replace the deprecated `decade_up` and `decade_down`?

https://github.com/matplotlib/matplotlib/pull/13413

I prefer using `matplotlib` implementations where possible, although it may not be worth the trouble for these simple functions to support both old and new versions of `matplotlib`.

**Comment by castillohair** [comment]
> Did you consider using the new `_decade_less_equal`, `_decade_greater_equal`, `_decade_less`, `_decade_greater` functions that were apparently introduced to replace the deprecated `decade_up` and `decade_down`?
>
> https://github.com/matplotlib/matplotlib/pull/13413

I'd rather not use hidden functions.

> it may not be worth the trouble for these simple functions to support both old and new versions of `matplotlib`.

This too.

**Review by JS3xton — APPROVED** [review]

**Pull request merged**
