### PR TITLE
Fixed file select box hanging after file selection on OSX. 

### LINKED ISSUE #299: askopenfilename() file selection box hangs after file selection in MacOS 10.13.6
After selecting an excel file through the file selection window generated by askopenfilename(), the window does not close until all flow files and the excel spreadsheet have been produced by excel_ui.py.

This is likely because tkinter in OSX waits till all processes are run in the main program thread before finishing its execution ([basis of hypothesis](https://stackoverflow.com/questions/16400533/why-ttk-progressbar-appears-after-process-in-tkinter)). 

By calling Tk().update() after askopenfilename(), the file selection box can be forced closed but this leaves a main tkinter window open which cannot be closed with Tk().withdraw() or Tk().iconify().

A proposed solution is to execute the tkinter GUI on a thread that is different from the main python execution thread (link to [threading](https://docs.python.org/2/library/threading.html?highlight=thread#threading.Thread)).

This file selection hang event was encountered in FlowCal 1.1.4 and 1.2.0 while running Anaconda2 5.1 (FlowCal 1.1.4) and Anaconda2 5.2 (FlowCal 1.2.0) in MacOS 10.13.6 (High Sierra).

### PR DESCRIPTION
**Pull request by felixekn**
Added a tkinter root window for the file select box to be placed into. This prevents the file select box from hanging after a file is selected. Tested on MacOSX 10.14.6 in python 3.7.4. Fixes #299

### CODE REVIEW

**Comment by castillohair** [comment]
Strangely enough, the issue is not present anymore in macOS Catalina 10.15 (or at least in my computer), that is, the open file window does not stick around even without your fix. I would still like to incorporate it since it's an issue in older macOS versions, and your version also seems to work fine in my computer (after applying #318). And the code seems cleaner than the previous version.

I successfully tested this on macOS Catalina 10.15 with python 3.7.2 (not anaconda). I also tested it with Anaconda 2019.07 on Windows 10 1903. 

My only issue is that you have incorporated this .DS_Store file that macOS insists on placing everywhere. Make an additional commit where you delete this file, and I'll be ready to accept it.

**Comment by castillohair** [comment]
@JS3xton  do you have any additional comments? I would like to merge and release quickly if possible.

**Comment by JS3xton** [comment]
Nope, go for it!

**Comment by felixekn** [comment]
commit 3bebb9582a2b9e0c01af0256bd972636b149b747 removed the .DS_Store located in the examples directory.

**Comment by castillohair** [comment]
@felixekn Please revert your edits on .gitignore. These are unrelated to this PR and have been already addressed in #318 more thoroughly.

**Comment by felixekn** [comment]
Edits reverted. Commit c21345d0a3de185f2c2104c28f8d5873174ac947 only removes .DS_Store from examples directory.

**Comment by castillohair** [comment]
Thanks! PR has just been accepted. I will release a new version with these and other changes in the next couple of days.

**Pull request merged**
